#!/bin/sh
#
load_virduino() {
	/bin/virduino_usb_ether_storage_init.sh
}
free_virduino() {
	/bin/virduino_usb_ether_storage_free.sh
}
case "$1" in
	start)
		load_virduino
		;;
	stop)
		free_virduino
		;;
	restart|reload)
		free_virduino
		load_virduino
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
